name: curtains
description: This will open my curtains.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  dartssh2: ^2.11.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  intl: ^0.20.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/icon_android.png"
  image_path_ios: "assets/icon_ios.png"

flutter:
  uses-material-design: true
  assets:
    - assets/.ssh/curt
