name: curtains
description: This will open my curtains.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  dartssh2: ^2.8.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/icon_android.png"
  image_path_ios: "assets/icon_ios.png"

flutter:
  uses-material-design: true
  assets:
    - assets/.ssh/curt



