name: curtains
description: This will open my curtains.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ssh: ^0.0.7
  rxdart: ^0.24.1
  shared_preferences: ^0.5.7+3
  flutter_secure_storage: ^3.3.3
  uuid: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.2
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path_android: "assets/icon_android.png"
  image_path_ios: "assets/icon_ios.png"

flutter:
  uses-material-design: true
  assets:
    - assets/.ssh/curt